import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 100, // Extra space for bottom tab bar
  },
  summaryRow: {
    flexDirection: "row",
    marginTop: 16,
    gap: 12,
  },
  summaryRowCompact: {
    flexDirection: "column",
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    gap: 6,
  },
  summaryLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
  },
  summaryMeta: {
    fontSize: 12,
    color: "#6B7280",
  },
  providersCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 18,
    marginTop: 20,
    gap: 14,
  },
  providersCardCompact: {
    flexDirection: "column",
  },
  providersCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  providersTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  providersSubtitle: {
    fontSize: 13,
    color: "#6B7280",
  },
  providerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFF7ED",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  providerBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#C2410C",
  },
  topProvider: {
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    gap: 6,
  },
  topProviderLabel: {
    fontSize: 12,
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  topProviderName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  topProviderMeta: {
    fontSize: 13,
    color: "#4B5563",
  },
  filterRow: {
    marginTop: 20,
  },
  filterChips: {
    paddingRight: 12,
    gap: 10,
  },
  filterChip: {
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginRight: 10,
  },
  filterChipActive: {
    backgroundColor: "#4338CA",
    borderColor: "#4338CA",
  },
  filterChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4B5563",
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  actionsRow: {
    marginTop: 18,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#4338CA",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  employeesList: {
    marginTop: 22,
    gap: 14,
  },
  employeeCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 18,
    gap: 14,
  },
  employeeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  employeeAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  employeeAvatarText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#4338CA",
  },
  employeeName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  employeeRole: {
    fontSize: 13,
    color: "#6B7280",
  },
  iconButton: {
    padding: 8,
  },
  employeeMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F9FAFB",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  metaChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
  },
  providersList: {
    marginTop: 30,
    gap: 12,
  },
  providersHeading: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  providerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    gap: 12,
  },
  providerName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  providerSpecialty: {
    fontSize: 13,
    color: "#6B7280",
  },
  providerContact: {
    fontSize: 12,
    color: "#4B5563",
    marginTop: 4,
  },
  providerStats: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  providerStatChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    flexShrink: 1,
  },
  providerStatText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4B5563",
    flexShrink: 1,
  },
  emptyState: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 40,
    alignItems: "center",
    gap: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "center",
    paddingHorizontal: 36,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 22,
    gap: 18,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  modalSection: {
    gap: 6,
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#111827",
  },
  buildingSelectRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  buildingChip: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  buildingChipActive: {
    borderColor: "#4338CA",
    backgroundColor: "#EEF2FF",
  },
  buildingChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4B5563",
  },
  buildingChipTextActive: {
    color: "#312E81",
  },
  shiftRow: {
    flexDirection: "row",
    gap: 10,
  },
  shiftChip: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#F9FAFB",
  },
  shiftChipActive: {
    backgroundColor: "#4338CA",
    borderColor: "#4338CA",
  },
  shiftChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4B5563",
  },
  shiftChipTextActive: {
    color: "#FFFFFF",
  },
});
