import type {
  User,
  Request,
  Notification,
  MaintenanceNotice,
  Amenity,
  AmenityBooking,
  Visitor,
  Rating,
  Building,
  Job,
  Analytics,
  RolePermissions,
  Permission,
  UnitType,
  BuildingUnit,
  BuildingEmployee,
  ServiceProviderProfile,
  ServiceProviderEmployee,
  ServiceProviderBuildingAssignment,
  VisitorLog,
  RatingSummary,
  Lease,
  VisitorPass,
  BuildingAmenityConfig,
} from "../types";

/**
 * TEST CREDENTIALS FOR MOCK LOGIN
 * ================================
 *
 * PASSWORD POLICY:
 * - For admin@towerdesk.com: Uses REAL backend API - requires actual password
 * - For ALL other accounts: Password is NOT validated - use ANY password
 *
 * This is mock authentication for development. See auth-context.tsx line 401.
 *
 * TENANT ACCOUNTS (use ANY password):
 * - tenant@demo.com (Ahmed Al-Rashid)
 * - tenant1@email.com (Sarah Mohammed)
 *
 * MANAGEMENT ACCOUNTS (use ANY password):
 * - management@demo.com (John Smith)
 *
 * ADMIN ACCOUNTS:
 * - admin@demo.com (Admin User) - use ANY password
 * - admin@towerdesk.com (Tower Desk Admin) - requires REAL password from backend
 * - superadmin@demo.com (Super Admin) - use ANY password
 *
 * SERVICE PROVIDER ACCOUNTS (use ANY password):
 * - sp1@demo.com (Mike Johnson - HVAC Technician)
 * - sp2@demo.com (Alex Wilson - Elevator Specialist)
 */

// Default users data
export const DEFAULT_USERS: Record<string, User> = {
  "tenant@demo.com": {
    id: "1",
    email: "tenant@demo.com",
    name: "Ahmed Al-Rashid",
    role: "tenant",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Ahmed Al-Rashid",
      apartment: "1205",
      tower: "Tower A",
      phone: "+971 50 123 4567",
      emergencyContact: "Fatima Al-Rashid",
      emergencyPhone: "+971 50 987 6543",
      buildingId: "building-1",
    },
  },
  "superadmin@demo.com": {
    id: "0",
    email: "superadmin@demo.com",
    name: "Super Admin",
    role: "super_admin",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Super Admin",
      phone: "+971 50 000 0000",
    },
  },
  "tenant1@email.com": {
    id: "6",
    email: "tenant1@email.com",
    name: "Sarah Mohammed",
    role: "tenant",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Sarah Mohammed",
      apartment: "804",
      tower: "Tower B",
      phone: "+971 50 234 5678",
      emergencyContact: "Omar Mohammed",
      emergencyPhone: "+971 50 876 5432",
      buildingId: "building-2",
    },
  },
  "management@demo.com": {
    id: "2",
    email: "management@demo.com",
    name: "John Smith",
    role: "management",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "John Smith",
      phone: "+971 50 345 6789",
      managedBuildingIds: ["building-1"],
    },
  },
  "admin@demo.com": {
    id: "3",
    email: "admin@demo.com",
    name: "Admin User",
    role: "admin",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Admin User",
      phone: "+971 50 456 7890",
    },
  },
  "admin@towerdesk.com": {
    id: "admin-live",
    email: "admin@towerdesk.com",
    name: "Tower Desk Admin",
    role: "admin",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Tower Desk Admin",
      phone: "+971 50 000 1234",
    },
  },
  "sp1@demo.com": {
    id: "4",
    email: "sp1@demo.com",
    name: "Mike Johnson",
    role: "service_provider",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Mike Johnson",
      phone: "+971 50 567 8901",
    },
  },
  "sp2@demo.com": {
    id: "5",
    email: "sp2@demo.com",
    name: "Alex Wilson",
    role: "service_provider",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Alex Wilson",
      phone: "+971 50 678 9012",
    },
  },
  "concierge@demo.com": {
    id: "building-emp-1",
    email: "concierge@demo.com",
    name: "Ali Hassan",
    role: "building_employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Ali Hassan",
      phone: "+971 50 111 2233",
      buildingId: "building-1",
      jobTitle: "Concierge",
    },
  },
  "housekeeping@demo.com": {
    id: "building-emp-2",
    email: "housekeeping@demo.com",
    name: "Maria Gomez",
    role: "building_employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Maria Gomez",
      phone: "+971 55 444 7788",
      buildingId: "building-1",
      jobTitle: "Housekeeping Lead",
    },
  },
  "security@demo.com": {
    id: "building-emp-3",
    email: "security@demo.com",
    name: "Omar Rahman",
    role: "building_employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Omar Rahman",
      phone: "+971 55 999 3344",
      buildingId: "building-2",
      jobTitle: "Security Supervisor",
    },
  },
  "employee1@demo.com": {
    id: "sp-emp-1",
    email: "employee1@demo.com",
    name: "Ahmed Al-Mansoori",
    role: "employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Ahmed Al-Mansoori",
      phone: "+971 50 111 2222",
      serviceProviderId: "4",
      serviceProviderName: "Mike Johnson",
      specialties: ["HVAC", "Electrical"],
      certifications: ["HVAC Level 2", "Electrical Safety"],
    },
  },
  "employee2@demo.com": {
    id: "sp-emp-2",
    email: "employee2@demo.com",
    name: "Rashid Ibrahim",
    role: "employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Rashid Ibrahim",
      phone: "+971 50 222 3333",
      serviceProviderId: "4",
      serviceProviderName: "Mike Johnson",
      specialties: ["Plumbing", "Carpentry"],
      certifications: ["Plumbing Professional"],
    },
  },
  "employee3@demo.com": {
    id: "sp-emp-3",
    email: "employee3@demo.com",
    name: "Khalid Hassan",
    role: "employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Khalid Hassan",
      phone: "+971 50 333 4444",
      serviceProviderId: "5",
      serviceProviderName: "Alex Wilson",
      specialties: ["Elevator Maintenance", "General Maintenance"],
      certifications: ["Elevator Safety Inspector", "Mechanical Systems"],
    },
  },
};

// Default requests data
export const DEFAULT_REQUESTS: Request[] = [
  {
    id: "1",
    title: "AC not working in living room",
    description:
      "The air conditioning unit in the living room has stopped working. It was making strange noises yesterday and now completely stopped.",
    type: "hvac",
    status: "pending",
    priority: "high",
    tenantId: "1",
    buildingId: "building-1",
    apartment: "1205",
    tower: "Tower A",
    contactPhone: "+971 50 123 4567",
    attachments: [],
    comments: [],
    slaDueAt: new Date(
      Date.now() - 2 * 24 * 60 * 60 * 1000 + 12 * 60 * 60 * 1000,
    ).toISOString(),
    lastEscalatedAt: undefined,
    messages: [],
    notes: [
      {
        id: "req-note-1",
        requestId: "1",
        authorId: "3",
        authorName: "Admin User",
        body: "Monitor HVAC vendor availability for emergency slot.",
        visibility: "management",
        createdAt: new Date(
          Date.now() - 36 * 60 * 60 * 1000,
        ).toISOString(),
      },
    ],
    timeline: [
      {
        id: "req-1-timeline-1",
        requestId: "1",
        eventType: "status_change",
        title: "Request Submitted",
        description: "Tenant reported the AC issue via mobile application.",
        createdAt: new Date(
          Date.now() - 2 * 24 * 60 * 60 * 1000,
        ).toISOString(),
      },
      {
        id: "req-1-timeline-2",
        requestId: "1",
        eventType: "sla",
        title: "SLA Target",
        description: "Resolve within 12 hours of submission.",
        metadata: { slaHours: 12 },
        createdAt: new Date(
          Date.now() - 2 * 24 * 60 * 60 * 1000,
        ).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Kitchen sink drainage issue",
    description:
      "Water is draining very slowly from the kitchen sink. There might be a blockage.",
    type: "plumbing",
    status: "in-progress",
    priority: "medium",
    tenantId: "1",
    assignedTo: "4",
    buildingId: "building-1",
    apartment: "1205",
    tower: "Tower A",
    contactPhone: "+971 50 123 4567",
    attachments: [],
    comments: [
      {
        id: "1",
        requestId: "2",
        userId: "4",
        userName: "Mike Johnson",
        message:
          "I will be there tomorrow morning to check the drainage system.",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        channel: "provider",
      },
    ],
    slaDueAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 24 * 60 * 60 * 1000).toISOString(),
    lastEscalatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    messages: [
      {
        id: "req-2-msg-1",
        requestId: "2",
        senderId: "1",
        senderName: "Sarah Mohammed",
        senderRole: "tenant",
        channel: "tenant",
        body: "Hi Mike, please let me know when you are on the way.",
        createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-2-msg-2",
        requestId: "2",
        senderId: "4",
        senderName: "Mike Johnson",
        senderRole: "service_provider",
        channel: "provider",
        body: "I'll arrive at 9am tomorrow. Please ensure access to the service closet.",
        createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
      },
    ],
    notes: [
      {
        id: "req-note-2",
        requestId: "2",
        authorId: "3",
        authorName: "Admin User",
        body: "Escalated to preferred vendor due to recurring drainage complaints.",
        visibility: "operations",
        createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
      },
    ],
    timeline: [
      {
        id: "req-2-timeline-1",
        requestId: "2",
        eventType: "status_change",
        title: "Request Submitted",
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-2-timeline-2",
        requestId: "2",
        eventType: "assignment",
        title: "Assigned to Mike Johnson",
        description: "HVAC specialist scheduled for follow-up visit.",
        actorId: "3",
        actorName: "Admin User",
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-2-timeline-3",
        requestId: "2",
        eventType: "escalation",
        title: "SLA Escalation Triggered",
        description: "Operations team alerted due to pending resolution.",
        createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Elevator maintenance request",
    description:
      "The elevator has been making unusual sounds and sometimes stops between floors.",
    type: "maintenance",
    status: "completed",
    priority: "urgent",
    tenantId: "6",
    assignedTo: "5",
    buildingId: "building-2",
    apartment: "804",
    tower: "Tower B",
    contactPhone: "+971 50 234 5678",
    attachments: [],
    comments: [
      {
        id: "2",
        requestId: "3",
        userId: "5",
        userName: "Alex Wilson",
        message: "Elevator has been fully serviced and tested. Issue resolved.",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        channel: "provider",
      },
    ],
    slaDueAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 24 * 60 * 60 * 1000).toISOString(),
    lastEscalatedAt: undefined,
    messages: [
      {
        id: "req-3-msg-1",
        requestId: "3",
        senderId: "6",
        senderName: "Sarah Mohammed",
        senderRole: "tenant",
        channel: "tenant",
        body: "Please ensure elevator is safe before weekend move-ins.",
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-3-msg-2",
        requestId: "3",
        senderId: "5",
        senderName: "Alex Wilson",
        senderRole: "service_provider",
        channel: "provider",
        body: "Maintenance completed. Certification uploaded to job record.",
        attachments: ["https://example.com/docs/elevator-cert.pdf"],
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    notes: [
      {
        id: "req-note-3",
        requestId: "3",
        authorId: "3",
        authorName: "Admin User",
        body: "Follow-up safety drill scheduled after maintenance completion.",
        visibility: "operations",
        createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      },
    ],
    timeline: [
      {
        id: "req-3-timeline-1",
        requestId: "3",
        eventType: "status_change",
        title: "Request Submitted",
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-3-timeline-2",
        requestId: "3",
        eventType: "assignment",
        title: "Assigned to Alex Wilson",
        actorId: "3",
        actorName: "Admin User",
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-3-timeline-3",
        requestId: "3",
        eventType: "status_change",
        title: "Marked Completed",
        description: "Elevator servicing completed and verified.",
        actorId: "5",
        actorName: "Alex Wilson",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "21",
    title: "Quarterly HVAC Service",
    description:
      "Scheduled HVAC filter maintenance and performance calibration for apartment 1205.",
    type: "hvac",
    status: "completed",
    priority: "medium",
    tenantId: "1",
    assignedTo: "4",
    buildingId: "building-1",
    apartment: "1205",
    tower: "Tower A",
    contactPhone: "+971 50 555 1122",
    attachments: [],
    slaDueAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    lastEscalatedAt: undefined,
    comments: [],
    messages: [
      {
        id: "req-21-msg-1",
        requestId: "21",
        senderId: "sp-emp-2",
        senderName: "Rashid Ibrahim",
        senderRole: "employee",
        channel: "provider",
        body: "Service complete. Awaiting tenant confirmation of airflow.",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    notes: [],
    timeline: [
      {
        id: "req-21-timeline-1",
        requestId: "21",
        eventType: "status_change",
        title: "Request Submitted",
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-21-timeline-2",
        requestId: "21",
        eventType: "assignment",
        title: "Assigned to HVAC Specialist",
        description: "Rashid Ibrahim scheduled for routine maintenance visit.",
        actorId: "3",
        actorName: "Admin User",
        createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-21-timeline-3",
        requestId: "21",
        eventType: "status_change",
        title: "Approved by Tenant",
        description: "Tenant confirmed the HVAC service and additional charges.",
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: "22",
    title: "Bathroom Leak Repair Follow-up",
    description:
      "Initial leak resolved. Contractor recommending waterproofing and tile replacement to prevent recurrence.",
    type: "plumbing",
    status: "in-progress",
    priority: "high",
    tenantId: "1",
    assignedTo: "4",
    buildingId: "building-1",
    apartment: "903",
    tower: "Tower A",
    contactPhone: "+971 50 123 4567",
    attachments: [],
    slaDueAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    lastEscalatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: "req-22-comment-1",
        requestId: "22",
        userId: "sp-emp-2",
        userName: "Rashid Ibrahim",
        message:
          "Additional sealant and tile labor required to complete waterproofing.",
        createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        channel: "provider",
      },
    ],
    messages: [
      {
        id: "req-22-msg-1",
        requestId: "22",
        senderId: "1",
        senderName: "Ahmed Al-Rashid",
        senderRole: "tenant",
        channel: "tenant",
        body: "Please share before/after photos so I can review before approving.",
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-22-msg-2",
        requestId: "22",
        senderId: "sp-emp-2",
        senderName: "Rashid Ibrahim",
        senderRole: "employee",
        channel: "provider",
        body: "Photos uploaded. Awaiting your go-ahead on the additional scope.",
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
    ],
    notes: [],
    timeline: [
      {
        id: "req-22-timeline-1",
        requestId: "22",
        eventType: "status_change",
        title: "Request Submitted",
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-22-timeline-2",
        requestId: "22",
        eventType: "assignment",
        title: "Assigned to Plumbing Specialist",
        description: "Work order assigned to Rashid Ibrahim for inspection.",
        actorId: "3",
        actorName: "Admin User",
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-22-timeline-3",
        requestId: "22",
        eventType: "status_change",
        title: "Awaiting Tenant Approval",
        description: "Completion submitted; tenant review pending for additional costs.",
        createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "23",
    title: "AC Drain Cleaning - Unit 904",
    description:
      "Condensate drain blocked causing overflow. Technician requested insulation wrap before restart.",
    type: "hvac",
    status: "in-progress",
    priority: "medium",
    tenantId: "1",
    assignedTo: "4",
    buildingId: "building-1",
    apartment: "904",
    tower: "Tower A",
    contactPhone: "+971 50 123 4567",
    attachments: [],
    slaDueAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    lastEscalatedAt: undefined,
    comments: [
      {
        id: "req-23-comment-1",
        requestId: "23",
        userId: "sp-emp-1",
        userName: "Ahmed Al-Mansoori",
        message:
          "Drain flushed. Need approval for insulation wrap before final sign-off.",
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        channel: "provider",
      },
    ],
    messages: [
      {
        id: "req-23-msg-1",
        requestId: "23",
        senderId: "1",
        senderName: "Ahmed Al-Rashid",
        senderRole: "tenant",
        channel: "tenant",
        body: "Please confirm if the leak risk is eliminated after the insulation.",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-23-msg-2",
        requestId: "23",
        senderId: "sp-emp-1",
        senderName: "Ahmed Al-Mansoori",
        senderRole: "employee",
        channel: "provider",
        body: "Yes, insulation prevents condensation dripping. Estimate submitted for approval.",
        createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      },
    ],
    notes: [],
    timeline: [
      {
        id: "req-23-timeline-1",
        requestId: "23",
        eventType: "status_change",
        title: "Request Submitted",
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-23-timeline-2",
        requestId: "23",
        eventType: "assignment",
        title: "Assigned to HVAC Technician",
        actorId: "3",
        actorName: "Admin User",
        createdAt: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "req-23-timeline-3",
        requestId: "23",
        eventType: "status_change",
        title: "Estimate Submitted",
        description: "Technician provided cost estimate awaiting approvals.",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Default notifications data
export const DEFAULT_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    userId: "1",
    title: "Request Status Update",
    message: "Your AC repair request has been assigned to a technician.",
    type: "info",
    read: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    userId: "1",
    title: "Maintenance Notice",
    message:
      "Scheduled water maintenance in Tower A from 9 AM to 12 PM tomorrow.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    userId: "1",
    title: "Request Completed",
    message: "Your kitchen sink drainage issue has been resolved.",
    type: "success",
    read: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    userId: "6",
    title: "Welcome!",
    message:
      "Welcome to Binghatti Concierge Services. Your account has been set up successfully.",
    type: "success",
    read: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    userId: "3",
    title: "SLA Breach Warning",
    message:
      "3 HVAC jobs are within 4 hours of breaching the 24h SLA. Reassign a technician to avoid penalties.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    userId: "3",
    title: "Revenue Snapshot Ready",
    message:
      "The weekly revenue report is final. Review the analytics dashboard to approve the executive summary.",
    type: "info",
    read: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
];

// Default maintenance notices data
export const DEFAULT_NOTICES: MaintenanceNotice[] = [
  {
    id: "1",
    title: "Water System Maintenance",
    description:
      "Scheduled maintenance of the water supply system. Water will be temporarily unavailable during the maintenance window.",
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    status: "scheduled",
    affectedAreas: ["Tower A", "Tower B"],
    estimatedDuration: "3 hours",
    createdBy: "2",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Elevator Inspection",
    description:
      "Annual safety inspection of all elevators. Service will be temporarily interrupted.",
    scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // Next week
    status: "scheduled",
    affectedAreas: ["All Towers"],
    estimatedDuration: "6 hours",
    createdBy: "2",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Parking Area Cleaning",
    description:
      "Deep cleaning of the parking areas. Please ensure your vehicles are moved to temporary parking.",
    scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // Yesterday
    status: "completed",
    affectedAreas: ["Basement Parking"],
    estimatedDuration: "4 hours",
    createdBy: "2",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "HVAC System Upgrade",
    description:
      "Installation of new energy-efficient HVAC units in Tower C. This will improve air quality and reduce energy consumption. Temporary disruption to cooling systems expected.",
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    status: "scheduled",
    affectedAreas: ["Tower C", "Lobby Areas"],
    estimatedDuration: "8 hours",
    createdBy: "2",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Default amenities data
export const DEFAULT_AMENITIES: Amenity[] = [
  {
    id: "1",
    buildingId: "building-1",
    amenityType: "pool",
    name: "Rooftop Swimming Pool",
    description: "Olympic-sized pool with stunning city views, heated in winter months.",
    capacity: 30,
    operatingHours: {
      monday: { open: "06:00", close: "22:00" },
      tuesday: { open: "06:00", close: "22:00" },
      wednesday: { open: "06:00", close: "22:00" },
      thursday: { open: "06:00", close: "22:00" },
      friday: { open: "06:00", close: "23:00" },
      saturday: { open: "06:00", close: "23:00" },
      sunday: { open: "06:00", close: "22:00" },
    },
    bookingDurationMinutes: 120,
    maxAdvanceBookingDays: 14,
    status: "active",
    imageUrl: "https://example.com/pool.jpg",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    buildingId: "building-1",
    amenityType: "gym",
    name: "Fitness Center",
    description: "Fully equipped gym with cardio machines, weights, and personal training services.",
    capacity: 20,
    operatingHours: {
      monday: { open: "05:00", close: "23:00" },
      tuesday: { open: "05:00", close: "23:00" },
      wednesday: { open: "05:00", close: "23:00" },
      thursday: { open: "05:00", close: "23:00" },
      friday: { open: "05:00", close: "23:00" },
      saturday: { open: "06:00", close: "22:00" },
      sunday: { open: "06:00", close: "22:00" },
    },
    bookingDurationMinutes: 90,
    maxAdvanceBookingDays: 7,
    status: "active",
    imageUrl: "https://example.com/gym.jpg",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    buildingId: "building-1",
    amenityType: "sauna",
    name: "Wellness Sauna",
    description: "Traditional Finnish sauna for relaxation and wellness.",
    capacity: 8,
    operatingHours: {
      monday: { open: "07:00", close: "21:00" },
      tuesday: { open: "07:00", close: "21:00" },
      wednesday: { open: "07:00", close: "21:00" },
      thursday: { open: "07:00", close: "21:00" },
      friday: { open: "07:00", close: "21:00" },
      saturday: { open: "08:00", close: "20:00" },
      sunday: { open: "08:00", close: "20:00" },
    },
    bookingDurationMinutes: 60,
    maxAdvanceBookingDays: 7,
    status: "active",
    imageUrl: "https://example.com/sauna.jpg",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    buildingId: "building-1",
    amenityType: "bbq",
    name: "Outdoor BBQ Area",
    description: "Covered BBQ area with grills, tables, and seating for outdoor gatherings.",
    capacity: 40,
    operatingHours: {
      monday: { open: "10:00", close: "22:00" },
      tuesday: { open: "10:00", close: "22:00" },
      wednesday: { open: "10:00", close: "22:00" },
      thursday: { open: "10:00", close: "22:00" },
      friday: { open: "10:00", close: "23:00" },
      saturday: { open: "10:00", close: "23:00" },
      sunday: { open: "10:00", close: "22:00" },
    },
    bookingDurationMinutes: 180,
    maxAdvanceBookingDays: 14,
    status: "active",
    imageUrl: "https://example.com/bbq.jpg",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Default bookings data
export const DEFAULT_BOOKINGS: AmenityBooking[] = [
  {
    id: "1",
    amenityId: "1",
    amenityName: "Rooftop Swimming Pool",
    amenityType: "pool",
    tenantId: "1",
    buildingId: "building-1",
    slotDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    slotTimeStart: "16:00",
    slotTimeEnd: "18:00",
    status: "confirmed",
    numberOfGuests: 4,
    bookingNotes: "Family swimming session",
    bookingCode: "POOL-20251005-001",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    amenityId: "2",
    amenityName: "Fitness Center",
    amenityType: "gym",
    tenantId: "1",
    buildingId: "building-1",
    slotDate: new Date().toISOString().split('T')[0],
    slotTimeStart: "07:00",
    slotTimeEnd: "08:30",
    status: "completed",
    numberOfGuests: 1,
    bookingNotes: "Morning workout",
    bookingCode: "GYM-20251003-015",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    amenityId: "4",
    amenityName: "Outdoor BBQ Area",
    amenityType: "bbq",
    tenantId: "6",
    buildingId: "building-1",
    slotDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    slotTimeStart: "18:00",
    slotTimeEnd: "21:00",
    status: "confirmed",
    numberOfGuests: 12,
    bookingNotes: "Birthday celebration",
    bookingCode: "BBQ-20251007-003",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Default visitors data
export const DEFAULT_VISITORS: Visitor[] = [
  {
    id: "1",
    tenantId: "1",
    buildingId: "building-1",
    unitNumber: "1205",
    visitorName: "Mohammed Hassan",
    visitorPhone: "+971 50 111 2222",
    visitorIdType: "national_id",
    visitorIdNumber: "784-1990-1234567-1",
    visitPurpose: "Family visit",
    expectedArrivalTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    expectedDepartureTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    status: "expected",
    visitorCode: "VST-20251002-001",
    qrCodeUrl: "https://example.com/qr/VST-20251002-001",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    tenantId: "1",
    buildingId: "building-1",
    unitNumber: "1205",
    visitorName: "John Delivery Service",
    visitorPhone: "+971 50 333 4444",
    visitorIdType: "driving_license",
    visitorIdNumber: "DL-123456",
    visitPurpose: "Package delivery",
    expectedArrivalTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expectedDepartureTime: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    actualArrivalTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    actualDepartureTime: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    status: "departed",
    visitorCode: "VST-20251002-002",
    qrCodeUrl: "https://example.com/qr/VST-20251002-002",
    checkedInBy: "security-1",
    checkedOutBy: "security-1",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    tenantId: "6",
    buildingId: "building-1",
    unitNumber: "804",
    visitorName: "AC Repair Technician",
    visitorPhone: "+971 50 555 6666",
    visitorIdType: "national_id",
    visitorIdNumber: "784-1988-7654321-2",
    visitPurpose: "AC maintenance",
    expectedArrivalTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    expectedDepartureTime: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: "expected",
    visitorCode: "VST-20251003-001",
    qrCodeUrl: "https://example.com/qr/VST-20251003-001",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Default ratings data
export const DEFAULT_RATINGS: Rating[] = [
  {
    id: "1",
    tenantId: "1",
    requestId: "2",
    serviceProviderId: "4",
    rating: 5,
    reviewText: "Excellent service! The plumber was professional and fixed the issue quickly.",
    attachments: [],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    tenantId: "6",
    requestId: "3",
    serviceProviderId: "5",
    buildingEmployeeId: "emp-1",
    rating: 4,
    reviewText: "Good work on the elevator. Everything is working smoothly now.",
    attachments: [],
    responseText: "Thank you for your feedback! We're glad the issue was resolved.",
    responseDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    respondedBy: "2",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Admin-specific mock data

// Service provider users (add to DEFAULT_USERS for role checking)
export const SERVICE_PROVIDER_USERS = {
  "sp1@demo.com": {
    id: "4",
    email: "sp1@demo.com",
    name: "Mike Johnson",
    role: "service_provider" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Mike Johnson",
      phone: "+971 50 567 8901",
    },
  },
  "sp2@demo.com": {
    id: "5",
    email: "sp2@demo.com",
    name: "Alex Wilson",
    role: "service_provider" as const,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      name: "Alex Wilson",
      phone: "+971 50 678 9012",
    },
  },
};

// Buildings data
export const DEFAULT_BUILDINGS: Building[] = [
  {
    id: "building-1",
    name: "Binghatti Tower A",
    address: "Sheikh Mohammed Bin Rashid Blvd",
    city: "Dubai",
    country: "UAE",
    managerId: "2",
    managerName: "John Smith",
    totalUnits: 150,
    occupiedUnits: 135,
    amenities: ["1", "2", "3", "4"],
    status: "active",
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "building-2",
    name: "Binghatti Tower B",
    address: "Sheikh Mohammed Bin Rashid Blvd",
    city: "Dubai",
    country: "UAE",
    managerId: undefined,
    managerName: undefined,
    totalUnits: 120,
    occupiedUnits: 110,
    amenities: ["1", "2"],
    status: "active",
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "building-3",
    name: "Binghatti Tower C",
    address: "Business Bay",
    city: "Dubai",
    country: "UAE",
    managerId: undefined,
    managerName: undefined,
    totalUnits: 200,
    occupiedUnits: 185,
    amenities: ["1", "2", "3"],
    status: "active",
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "building-4",
    name: "Binghatti Residence",
    address: "JBR Walk",
    city: "Dubai",
    country: "UAE",
    totalUnits: 80,
    occupiedUnits: 75,
    amenities: ["1"],
    status: "maintenance",
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEFAULT_UNIT_TYPES: UnitType[] = [
  {
    id: "unit-type-studio",
    name: "Studio",
    bedrooms: 0,
    bathrooms: 1,
    areaSqFt: 480,
    baseRent: 4500,
    amenities: ["balcony", "city-view"],
  },
  {
    id: "unit-type-1bhk",
    name: "1 Bedroom",
    bedrooms: 1,
    bathrooms: 1,
    areaSqFt: 720,
    baseRent: 6500,
    amenities: ["balcony", "built-in-wardrobe"],
  },
  {
    id: "unit-type-2bhk",
    name: "2 Bedroom",
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1020,
    baseRent: 9200,
    amenities: ["maid-room", "parking", "sea-view"],
  },
];

export const DEFAULT_BUILDING_UNITS: BuildingUnit[] = [
  {
    id: "unit-a-1205",
    buildingId: "building-1",
    unitNumber: "1205",
    floor: 12,
    typeId: "unit-type-2bhk",
    templateId: "unit-type-2bhk",
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1240,
    status: "occupied",
    tenantId: "1",
    amenities: ["balcony", "parking", "smart-lock"],
    photos: [
      "https://example.com/images/units/1205-living.jpg",
      "https://example.com/images/units/1205-view.jpg",
    ],
    rentAmount: 8500,
    lastInspectionDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "unit-a-1206",
    buildingId: "building-1",
    unitNumber: "1206",
    floor: 12,
    typeId: "unit-type-1bhk",
    templateId: "unit-type-1bhk",
    bedrooms: 1,
    bathrooms: 1,
    areaSqFt: 760,
    status: "vacant",
    amenities: ["balcony", "city-view"],
    photos: [
      "https://example.com/images/units/1206-living.jpg",
    ],
    rentAmount: 6900,
    lastInspectionDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 320 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "unit-b-804",
    buildingId: "building-2",
    unitNumber: "804",
    floor: 8,
    typeId: "unit-type-1bhk",
    templateId: "unit-type-1bhk",
    bedrooms: 1,
    bathrooms: 1,
    areaSqFt: 720,
    status: "occupied",
    tenantId: "6",
    amenities: ["parking"],
    photos: [
      "https://example.com/images/units/804-bedroom.jpg",
    ],
    rentAmount: 6700,
    lastInspectionDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 280 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "unit-b-305",
    buildingId: "building-2",
    unitNumber: "305",
    floor: 3,
    typeId: "unit-type-studio",
    templateId: "unit-type-studio",
    bedrooms: 0,
    bathrooms: 1,
    areaSqFt: 480,
    status: "maintenance",
    amenities: ["city-view"],
    photos: [],
    offlineReason: "Renovation - bathroom upgrade",
    lastInspectionDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "unit-c-1902",
    buildingId: "building-3",
    unitNumber: "1902",
    floor: 19,
    typeId: "unit-type-2bhk",
    templateId: "unit-type-2bhk",
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1325,
    status: "vacant",
    amenities: ["sea-view", "parking"],
    photos: [
      "https://example.com/images/units/1902-view.jpg",
    ],
    rentAmount: 9800,
    lastInspectionDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEFAULT_LEASES: Lease[] = [
  {
    id: "lease-1205-2024",
    buildingId: "building-1",
    unitId: "unit-a-1205",
    tenantId: "1",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    rentAmount: 8500,
    depositAmount: 8500,
    status: "active",
    documents: ["https://example.com/leases/lease-1205.pdf"],
    notes: "Renewal notice due 60 days before expiry.",
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "lease-804-2024",
    buildingId: "building-2",
    unitId: "unit-b-804",
    tenantId: "6",
    startDate: "2023-10-01",
    endDate: "2024-09-30",
    rentAmount: 6700,
    depositAmount: 6700,
    status: "notice",
    documents: ["https://example.com/leases/lease-804.pdf"],
    notes: "Tenant requested renewal with rent review.",
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "lease-1206-2025",
    buildingId: "building-1",
    unitId: "unit-a-1206",
    tenantId: "prospect-1001",
    startDate: "2025-01-15",
    endDate: "2025-12-31",
    rentAmount: 7000,
    depositAmount: 7000,
    status: "scheduled",
    documents: [],
    notes: "Prospective tenant awaiting final approval.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_AMENITY_CONFIGS: BuildingAmenityConfig[] = [
  {
    id: "amenity-config-pool-a",
    buildingId: "building-1",
    amenityId: "amenity-pool",
    amenityName: "Sky Pool",
    bookingWindowDays: 14,
    maxDurationMinutes: 90,
    maxConcurrentBookings: 6,
    advanceCancellationHours: 4,
    status: "active",
    rules: [
      {
        id: "rule-1",
        label: "Maximum 4 guests per unit",
        description: "Children under 12 must be accompanied by an adult.",
      },
      {
        id: "rule-2",
        label: "No food or glassware",
      },
    ],
    maintenanceWindow: {
      start: "2024-11-18T08:00:00.000Z",
      end: "2024-11-18T10:00:00.000Z",
      notes: "Weekly cleaning. Bookings blocked automatically.",
    },
    imageUrl: "https://example.com/images/amenities/pool.jpg",
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "amenity-config-gym-a",
    buildingId: "building-1",
    amenityId: "amenity-gym",
    amenityName: "Fitness Studio",
    bookingWindowDays: 7,
    maxDurationMinutes: 60,
    maxConcurrentBookings: 10,
    advanceCancellationHours: 2,
    status: "active",
    rules: [
      {
        id: "rule-1",
        label: "No outdoor footwear",
      },
      {
        id: "rule-2",
        label: "Sanitize equipment after use",
      },
    ],
    createdAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "amenity-config-bbq-b",
    buildingId: "building-2",
    amenityId: "amenity-bbq",
    amenityName: "BBQ Terrace",
    bookingWindowDays: 10,
    maxDurationMinutes: 180,
    maxConcurrentBookings: 2,
    advanceCancellationHours: 12,
    status: "maintenance",
    rules: [
      {
        id: "rule-1",
        label: "Clean-up required",
        description: "Security deposit forfeited if area left uncleaned.",
      },
    ],
    maintenanceWindow: {
      start: "2024-11-20T05:00:00.000Z",
      end: "2024-11-23T17:00:00.000Z",
      notes: "Deck resurfacing in progress.",
    },
    createdAt: new Date(Date.now() - 210 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEFAULT_VISITOR_PASSES: VisitorPass[] = [
  {
    id: "visitor-pass-1",
    buildingId: "building-1",
    tenantId: "1",
    unitNumber: "1205",
    type: "visitor",
    name: "Michael Brown",
    contactPhone: "+971 55 000 1122",
    scheduledStart: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    scheduledEnd: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    qrCodeUrl: "https://example.com/pass/visitor-pass-1",
    notes: "Guest for dinner.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "visitor-pass-2",
    buildingId: "building-1",
    tenantId: "1",
    unitNumber: "1205",
    type: "delivery",
    name: "Aramex Courier",
    company: "Aramex",
    scheduledStart: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    scheduledEnd: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "completed",
    notes: "Delivered furniture to resident.",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "visitor-pass-3",
    buildingId: "building-2",
    tenantId: "6",
    unitNumber: "804",
    type: "contractor",
    name: "Zaid Contractors",
    contactPhone: "+971 52 333 5566",
    scheduledStart: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    scheduledEnd: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    status: "approved",
    notes: "HVAC maintenance scheduled.",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_BUILDING_EMPLOYEES: BuildingEmployee[] = [
  {
    id: "emp-1",
    buildingId: "building-1",
    userId: "building-emp-1",
    name: "Ali Hassan",
    role: "Concierge",
    phone: "+971 50 111 2233",
    shift: "morning",
    rating: 4.8,
    jobsCompleted: 120,
  },
  {
    id: "emp-2",
    buildingId: "building-1",
    userId: "building-emp-2",
    name: "Maria Gomez",
    role: "Housekeeping Lead",
    phone: "+971 55 444 7788",
    shift: "evening",
    rating: 4.6,
    jobsCompleted: 98,
  },
  {
    id: "emp-3",
    buildingId: "building-2",
    userId: "building-emp-3",
    name: "Omar Rahman",
    role: "Security Supervisor",
    phone: "+971 55 999 3344",
    shift: "night",
    rating: 4.7,
    jobsCompleted: 140,
  },
];

export const DEFAULT_SERVICE_PROVIDERS_PROFILES: ServiceProviderProfile[] = [
  {
    id: "sp-profile-1",
    userId: "4",
    name: "CoolTech HVAC Services LLC",
    specialty: "HVAC & Climate Control",
    phone: "+971 4 567 8901",
    email: "contact@cooltech-uae.com",
    rating: 4.9,
    jobsCompleted: 320,
    responseTimeMinutes: 45,
  },
  {
    id: "sp-profile-2",
    userId: "5",
    name: "VerticalRise Elevator Solutions",
    specialty: "Elevator Maintenance & Repair",
    phone: "+971 4 678 9012",
    email: "service@verticalrise.ae",
    rating: 4.7,
    jobsCompleted: 285,
    responseTimeMinutes: 60,
  },
  {
    id: "sp-profile-3",
    name: "AquaFlow Plumbing & Drainage Co.",
    specialty: "Plumbing & Water Systems",
    phone: "+971 4 789 0123",
    email: "support@aquaflow.ae",
    rating: 4.8,
    jobsCompleted: 412,
    responseTimeMinutes: 30,
  },
];

export const DEFAULT_SERVICE_PROVIDER_EMPLOYEES: ServiceProviderEmployee[] = [
  {
    id: "sp-emp-1",
    serviceProviderId: "sp-profile-1", // CoolTech HVAC Services
    name: "Ahmed Al-Mansoori",
    phone: "+971 55 123 4567",
    email: "ahmed@cooltech-uae.com",
    specialty: "Senior HVAC Technician",
    status: "active",
    rating: 4.8,
    jobsCompleted: 78,
    certifications: ["HVAC Level 2", "Refrigeration Specialist"],
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-2",
    serviceProviderId: "sp-profile-1", // CoolTech HVAC Services
    name: "Rashid Ibrahim",
    phone: "+971 55 234 5678",
    email: "rashid@cooltech-uae.com",
    specialty: "HVAC Technician",
    status: "active",
    rating: 4.6,
    jobsCompleted: 62,
    certifications: ["HVAC Level 1", "AC Installation"],
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-3",
    serviceProviderId: "sp-profile-2", // VerticalRise Elevator Solutions
    name: "Khalid Hassan",
    phone: "+971 55 345 6789",
    email: "khalid@verticalrise.ae",
    specialty: "Lead Elevator Technician",
    status: "active",
    rating: 4.9,
    jobsCompleted: 95,
    certifications: ["Elevator Safety Certification", "Lift Maintenance Expert"],
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-4",
    serviceProviderId: "sp-profile-2", // VerticalRise Elevator Solutions
    name: "Mohammed Saeed",
    phone: "+971 55 456 7890",
    email: "mohammed@verticalrise.ae",
    specialty: "Elevator Maintenance Technician",
    status: "active",
    rating: 4.5,
    jobsCompleted: 58,
    certifications: ["General Maintenance", "Electrical Safety"],
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-5",
    serviceProviderId: "sp-profile-3", // AquaFlow Plumbing & Drainage
    name: "Youssef Rahman",
    phone: "+971 55 567 8901",
    email: "youssef@aquaflow.ae",
    specialty: "Master Plumber",
    status: "active",
    rating: 4.9,
    jobsCompleted: 104,
    certifications: ["Master Plumbing License", "Water Systems Expert"],
    createdAt: new Date(Date.now() - 240 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-6",
    serviceProviderId: "sp-profile-3", // AquaFlow Plumbing & Drainage
    name: "Omar Al-Falasi",
    phone: "+971 55 678 9012",
    email: "omar@aquaflow.ae",
    specialty: "Drainage Specialist",
    status: "active",
    rating: 4.7,
    jobsCompleted: 86,
    certifications: ["Plumbing Certification", "Drainage Systems"],
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sp-emp-7",
    serviceProviderId: "sp-profile-1", // CoolTech HVAC Services
    name: "Samir Patel",
    phone: "+971 55 789 0123",
    email: "samir@cooltech-uae.com",
    specialty: "Climate Control Specialist",
    status: "active",
    rating: 4.8,
    jobsCompleted: 71,
    certifications: ["Smart HVAC Systems", "Energy Efficiency Expert"],
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEFAULT_SERVICE_PROVIDER_BUILDING_ASSIGNMENTS: ServiceProviderBuildingAssignment[] = [
  {
    id: "sp-assign-1",
    serviceProviderId: "sp-profile-1", // CoolTech HVAC Services
    buildingId: "building-1", // Binghatti Tower A
    assignedBy: "1", // Super Admin
    assignedByName: "Admin User",
    assignedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["HVAC", "Air Conditioning", "Ventilation"],
    notes: "Primary HVAC provider for Tower A",
  },
  {
    id: "sp-assign-2",
    serviceProviderId: "sp-profile-1", // CoolTech HVAC Services
    buildingId: "building-2", // Binghatti Tower B
    assignedBy: "1", // Super Admin
    assignedByName: "Admin User",
    assignedAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["HVAC", "Air Conditioning"],
    notes: "Climate control for Tower B",
  },
  {
    id: "sp-assign-3",
    serviceProviderId: "sp-profile-2", // VerticalRise Elevator Solutions
    buildingId: "building-1", // Binghatti Tower A
    assignedBy: "2", // John Smith (Building Manager)
    assignedByName: "John Smith",
    assignedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["Elevator Maintenance", "Elevator Repair"],
    notes: "Annual elevator maintenance contract",
  },
  {
    id: "sp-assign-4",
    serviceProviderId: "sp-profile-2", // VerticalRise Elevator Solutions
    buildingId: "building-3", // Binghatti Plaza
    assignedBy: "1", // Super Admin
    assignedByName: "Admin User",
    assignedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["Elevator Maintenance"],
    notes: "Plaza elevator service contract",
  },
  {
    id: "sp-assign-5",
    serviceProviderId: "sp-profile-3", // AquaFlow Plumbing & Drainage
    buildingId: "building-1", // Binghatti Tower A
    assignedBy: "2", // John Smith (Building Manager)
    assignedByName: "John Smith",
    assignedAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["Plumbing", "Water Systems", "Drainage"],
    notes: "Primary plumbing contractor for Tower A",
  },
  {
    id: "sp-assign-6",
    serviceProviderId: "sp-profile-3", // AquaFlow Plumbing & Drainage
    buildingId: "building-3", // Binghatti Plaza
    assignedBy: "1", // Super Admin
    assignedByName: "Admin User",
    assignedAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    specialties: ["Plumbing", "Drainage Systems"],
    notes: "Plumbing services for Plaza complex",
  },
];

export const DEFAULT_VISITOR_LOGS: VisitorLog[] = [
  {
    id: "visitor-1",
    buildingId: "building-1",
    tenantId: "1",
    unitNumber: "1205",
    type: "visitor",
    name: "Fatima Al-Khatib",
    expectedArrival: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    checkInTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: "checked_in",
    notes: "Family friend visiting for lunch",
  },
  {
    id: "visitor-2",
    buildingId: "building-1",
    tenantId: "1",
    unitNumber: "1205",
    type: "delivery",
    name: "Talabat Courier",
    company: "Talabat",
    expectedArrival: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    checkInTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    checkOutTime: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    status: "completed",
    notes: "Food delivery",
  },
  {
    id: "visitor-3",
    buildingId: "building-2",
    tenantId: "6",
    unitNumber: "804",
    type: "visitor",
    name: "Omar Mohammed",
    expectedArrival: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: "expected",
    notes: "Family visit",
  },
];

export const DEFAULT_RATING_SUMMARIES: RatingSummary[] = [
  {
    id: "rating-summary-sp1",
    entityId: "sp-profile-1",
    entityName: "Mike Johnson",
    role: "service_provider",
    averageRating: 4.9,
    reviewsCount: 86,
    lastReviewDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "rating-summary-emp1",
    entityId: "emp-1",
    entityName: "Ali Hassan",
    role: "employee",
    averageRating: 4.8,
    reviewsCount: 63,
    lastReviewDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Jobs data
export const DEFAULT_JOBS: Job[] = [
  {
    id: "job-1",
    requestId: "1",
    title: "AC Repair - Unit 1205",
    description: "AC unit in living room not working. Needs immediate attention.",
    type: "hvac",
    status: "assigned",
    priority: "high",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    unitNumber: "1205",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    assignedToEmployeeId: "sp-emp-1",
    assignedToEmployeeName: "Ahmed Al-Mansoori",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [
      {
        id: "note-1",
        jobId: "job-1",
        userId: "4",
        userName: "Mike Johnson",
        note: "Parts ordered, will fix tomorrow morning",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    estimatedCost: 500,
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-1-cost-1",
        label: "Diagnostics Visit",
        amount: 150,
        category: "labor",
      },
      {
        id: "job-1-cost-2",
        label: "Compressor Replacement Parts",
        amount: 350,
        category: "parts",
        description: "OEM compressor kit",
      },
    ],
    complianceChecklist: [
      {
        id: "job-1-check-1",
        label: "Electrical isolation verified",
        completed: true,
        completedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        completedBy: "4",
      },
      {
        id: "job-1-check-2",
        label: "Post-repair temperature test",
        completed: false,
        notes: "To be performed after part replacement",
      },
    ],
    assignmentHistory: [
      {
        id: "job-1-assign-1",
        targetType: "service_provider",
        serviceProviderId: "4",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
        status: "pending",
      },
    ],
    assignmentQueue: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-2",
    requestId: "2",
    title: "Plumbing - Kitchen Sink Unit 1205",
    description: "Kitchen sink drainage issue, slow draining water",
    type: "plumbing",
    status: "in-progress",
    priority: "medium",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    unitNumber: "1205",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    assignedToEmployeeId: "sp-emp-2",
    assignedToEmployeeName: "Rashid Ibrahim",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [],
    estimatedCost: 200,
    scheduledDate: new Date().toISOString(),
    costBreakdown: [
      {
        id: "job-2-cost-1",
        label: "Pipe flush chemicals",
        amount: 80,
        category: "parts",
      },
      {
        id: "job-2-cost-2",
        label: "Labor - 2 hours",
        amount: 120,
        category: "labor",
      },
    ],
    complianceChecklist: [
      {
        id: "job-2-check-1",
        label: "Water shutoff confirmed",
        completed: true,
        completedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        completedBy: "4",
      },
      {
        id: "job-2-check-2",
        label: "Drainage restored",
        completed: false,
      },
    ],
    assignmentHistory: [
      {
        id: "job-2-assign-1",
        targetType: "service_provider",
        serviceProviderId: "4",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date().toISOString(),
        status: "accepted",
        notes: "Tenant prefers morning slot.",
      },
    ],
    assignmentQueue: [],
    additionalCosts: [
      {
        id: "cost-1",
        jobId: "job-2",
        employeeId: "sp-emp-2",
        employeeName: "Rashid Ibrahim",
        amount: 75,
        description: "Extra pipe section needed for replacement",
        category: "parts",
        status: "pending",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "cost-2",
        jobId: "job-2",
        employeeId: "sp-emp-2",
        employeeName: "Rashid Ibrahim",
        amount: 50,
        description: "Additional labor for removing old pipe",
        category: "labor",
        status: "approved",
        approvedBy: "4",
        approvedByName: "Mike Johnson",
        approvedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      },
    ],
    startedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    startedBy: "sp-emp-2",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-3",
    requestId: "3",
    title: "Elevator Maintenance - Tower B",
    description: "Elevator making unusual sounds, safety inspection needed",
    type: "maintenance",
    status: "completed",
    priority: "urgent",
    buildingId: "building-2",
    buildingName: "Binghatti Tower B",
    unitNumber: "804",
    assignedTo: "5",
    assignedToName: "Alex Wilson",
    assignedToEmployeeId: "sp-emp-3",
    assignedToEmployeeName: "Khalid Hassan",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 6.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [
      {
        id: "note-2",
        jobId: "job-3",
        userId: "5",
        userName: "Alex Wilson",
        note: "Completed full inspection and maintenance",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    estimatedCost: 1500,
    actualCost: 1400,
    scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completedDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-3-cost-1",
        label: "Safety inspection",
        amount: 600,
        category: "labor",
      },
      {
        id: "job-3-cost-2",
        label: "Replacement rollers",
        amount: 800,
        category: "parts",
      },
    ],
    complianceChecklist: [
      {
        id: "job-3-check-1",
        label: "Emergency brake test",
        completed: true,
        completedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        completedBy: "5",
      },
      {
        id: "job-3-check-2",
        label: "Safety certificate uploaded",
        completed: true,
        completedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        completedBy: "5",
        notes: "Certificate ID: ELV-9934",
      },
    ],
    assignmentHistory: [
      {
        id: "job-3-assign-1",
        targetType: "service_provider",
        serviceProviderId: "5",
        serviceProviderName: "Alex Wilson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        status: "completed",
      },
    ],
    assignmentQueue: [],
    completionPhotos: [
      {
        id: "photo-1",
        jobId: "job-3",
        employeeId: "sp-emp-3",
        employeeName: "Khalid Hassan",
        uri: "https://picsum.photos/400/300?random=1",
        caption: "Elevator rollers replaced - before",
        uploadedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "photo-2",
        jobId: "job-3",
        employeeId: "sp-emp-3",
        employeeName: "Khalid Hassan",
        uri: "https://picsum.photos/400/300?random=2",
        caption: "New rollers installed - after",
        uploadedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "photo-3",
        jobId: "job-3",
        employeeId: "sp-emp-3",
        employeeName: "Khalid Hassan",
        uri: "https://picsum.photos/400/300?random=3",
        caption: "Safety brake test documentation",
        uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    completionStatus: "tenant_approved",
    completionApprovedBy: "tenant-1",
    completionApprovedByName: "Sarah Johnson",
    completionApprovedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    startedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    startedBy: "sp-emp-3",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-4",
    title: "Pool Cleaning - Tower A",
    description: "Regular monthly pool cleaning and chemical balancing",
    type: "maintenance",
    status: "assigned",
    priority: "low",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [],
    estimatedCost: 300,
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-4-cost-1",
        label: "Cleaning supplies",
        amount: 120,
        category: "parts",
      },
      {
        id: "job-4-cost-2",
        label: "Technician labor",
        amount: 180,
        category: "labor",
      },
    ],
    complianceChecklist: [
      {
        id: "job-4-check-1",
        label: "Chemical balance recorded",
        completed: false,
      },
    ],
    assignmentHistory: [],
    assignmentQueue: [
      {
        id: "job-4-assign-queue-1",
        targetType: "service_provider",
        serviceProviderId: "sp-profile-1",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        status: "pending",
        notes: "Pending confirmation of crew availability.",
      },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-5",
    title: "Electrical - Common Area Tower C",
    description: "Replace faulty lighting in lobby area",
    type: "electrical",
    status: "assigned",
    priority: "medium",
    buildingId: "building-3",
    buildingName: "Binghatti Tower C",
    assignedTo: "5",
    assignedToName: "Alex Wilson",
    assignedToEmployeeId: "sp-emp-4",
    assignedToEmployeeName: "Mohammed Saeed",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "2",
    attachments: [],
    notes: [],
    estimatedCost: 800,
    scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-5-cost-1",
        label: "LED fixtures",
        amount: 500,
        category: "parts",
      },
      {
        id: "job-5-cost-2",
        label: "Installation labor",
        amount: 300,
        category: "labor",
      },
    ],
    complianceChecklist: [
      {
        id: "job-5-check-1",
        label: "Permit verified",
        completed: true,
        completedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        completedBy: "2",
      },
      {
        id: "job-5-check-2",
        label: "As-built photos uploaded",
        completed: false,
      },
    ],
    assignmentHistory: [
      {
        id: "job-5-assign-1",
        targetType: "service_provider",
        serviceProviderId: "5",
        serviceProviderName: "Alex Wilson",
        assignedBy: "2",
        assignedByName: "John Smith",
        assignedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        status: "pending",
      },
    ],
    assignmentQueue: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job-employee2-complete",
    requestId: "21",
    title: "HVAC Filter Replacement - Unit 1205",
    description:
      "Quarterly HVAC service completed with filter replacement and airflow calibration.",
    type: "hvac",
    status: "completed",
    priority: "medium",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    unitNumber: "1205",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    assignedToEmployeeId: "sp-emp-2",
    assignedToEmployeeName: "Rashid Ibrahim",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [
      {
        id: "job-employee2-note-1",
        jobId: "job-employee2-complete",
        userId: "sp-emp-2",
        userName: "Rashid Ibrahim",
        note: "Completed filter swap and verified thermostat calibration.",
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
    ],
    estimatedCost: 350,
    actualCost: 365,
    scheduledDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-employee2-complete-cost-1",
        label: "Filter set",
        amount: 120,
        category: "parts",
      },
      {
        id: "job-employee2-complete-cost-2",
        label: "Labor",
        amount: 230,
        category: "labor",
        description: "Two-hour service visit",
      },
      {
        id: "job-employee2-complete-cost-3",
        label: "Calibration check",
        amount: 15,
        category: "fees",
      },
    ],
    complianceChecklist: [
      {
        id: "job-employee2-complete-check-1",
        label: "Power isolation completed",
        completed: true,
        completedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
        completedBy: "sp-emp-2",
      },
      {
        id: "job-employee2-complete-check-2",
        label: "Airflow test recorded",
        completed: true,
        completedAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
        completedBy: "sp-emp-2",
      },
    ],
    assignmentHistory: [
      {
        id: "job-employee2-complete-assign-1",
        targetType: "service_provider",
        serviceProviderId: "4",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        status: "completed",
      },
    ],
    assignmentQueue: [],
    completionPhotos: [
      {
        id: "job-employee2-complete-photo-1",
        jobId: "job-employee2-complete",
        employeeId: "sp-emp-2",
        employeeName: "Rashid Ibrahim",
        uri: "https://picsum.photos/400/300?random=41",
        caption: "New filter installed",
        uploadedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "job-employee2-complete-photo-2",
        jobId: "job-employee2-complete",
        employeeId: "sp-emp-2",
        employeeName: "Rashid Ibrahim",
        uri: "https://picsum.photos/400/300?random=42",
        caption: "Airflow reading after service",
        uploadedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      },
    ],
    completionStatus: "tenant_approved",
    completionApprovedBy: "tenant-1",
    completionApprovedByName: "Sarah Johnson",
    completionApprovedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    completionNotes: "Filter replaced and airflow calibrated.",
    tenantName: "Sarah Johnson",
    tenantPhone: "+971 50 555 1122",
    estimate: {
      id: "job-employee2-estimate",
      jobId: "job-employee2-complete",
      createdBy: "sp-emp-2",
      createdByName: "Rashid Ibrahim",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      status: "tenant_approved",
      items: [
        {
          id: "job-employee2-estimate-item-1",
          label: "Filter set",
          amount: 120,
          category: "parts",
          description: "Replacement filters for both intake units",
        },
        {
          id: "job-employee2-estimate-item-2",
          label: "Labor",
          amount: 230,
          category: "labor",
          description: "Two-hour scheduled maintenance visit",
        },
        {
          id: "job-employee2-estimate-item-3",
          label: "Calibration check",
          amount: 15,
          category: "fees",
          description: "Calibrated thermostat and documented airflow",
        },
      ],
      subtotal: 365,
      notes: "Includes filter replacements and calibration verification.",
      updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      spApprovedBy: "4",
      spApprovedByName: "Mike Johnson",
      spDecisionAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      tenantDecisionBy: "tenant-1",
      tenantDecisionByName: "Sarah Johnson",
      tenantDecisionAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    startedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    startedBy: "sp-emp-2",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "job-tenant-cost-review",
    requestId: "22",
    title: "Bathroom Leak Repair - Unit 903",
    description:
      "Leak traced to damaged vanity plumbing; additional sealant and tile replacement required.",
    type: "plumbing",
    status: "assigned",
    priority: "high",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    unitNumber: "903",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    assignedToEmployeeId: "sp-emp-2",
    assignedToEmployeeName: "Rashid Ibrahim",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 5.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [],
    estimatedCost: 280,
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-tenant-cost-review-cost-1",
        label: "Initial diagnostics",
        amount: 120,
        category: "labor",
      },
    ],
    complianceChecklist: [
      {
        id: "job-tenant-cost-review-check-1",
        label: "Water supply isolated",
        completed: true,
        completedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
        completedBy: "sp-emp-2",
      },
      {
        id: "job-tenant-cost-review-check-2",
        label: "Moisture test",
        completed: true,
        completedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        completedBy: "sp-emp-2",
        notes: "Dry after 2-hour observation window.",
      },
    ],
    assignmentHistory: [
      {
        id: "job-tenant-cost-review-assign-1",
        targetType: "service_provider",
        serviceProviderId: "4",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        status: "completed",
      },
    ],
    assignmentQueue: [],
    tenantName: "Ahmed Al-Rashid",
    tenantPhone: "+971 50 123 4567",
    estimate: {
      id: "job-tenant-cost-review-estimate",
      jobId: "job-tenant-cost-review",
      createdBy: "sp-emp-2",
      createdByName: "Rashid Ibrahim",
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      status: "sp_approved",
      items: [
        {
          id: "job-tenant-cost-review-estimate-item-1",
          label: "Waterproof sealant kit",
          amount: 95,
          category: "materials",
          description: "Premium waterproof sealant for vanity base.",
        },
        {
          id: "job-tenant-cost-review-estimate-item-2",
          label: "Tile replacement labor",
          amount: 90,
          category: "labor",
          description: "Remove and replace two damaged tiles.",
        },
      ],
      subtotal: 185,
      notes:
        "Recommended to prevent recurring moisture damage before resuming normal use.",
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      spApprovedBy: "4",
      spApprovedByName: "Mike Johnson",
      spDecisionAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "job-additional-cost-demo",
    requestId: "23",
    title: "AC Drain Cleaning - Unit 904",
    description:
      "Condensate drain requires cleaning and insulation to prevent ceiling leaks.",
    type: "hvac",
    status: "in-progress",
    priority: "medium",
    buildingId: "building-1",
    buildingName: "Binghatti Tower A",
    unitNumber: "904",
    assignedTo: "4",
    assignedToName: "Mike Johnson",
    assignedToEmployeeId: "sp-emp-1",
    assignedToEmployeeName: "Ahmed Al-Mansoori",
    offerStatus: "accepted",
    offeredAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: "3",
    attachments: [],
    notes: [
      {
        id: "job-additional-cost-demo-note-1",
        jobId: "job-additional-cost-demo",
        userId: "sp-emp-1",
        userName: "Ahmed Al-Mansoori",
        note: "Initial inspection completed, need insulation wrap.",
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      },
    ],
    estimatedCost: 220,
    scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    costBreakdown: [
      {
        id: "job-additional-cost-demo-cost-1",
        label: "Drain flush labor",
        amount: 120,
        category: "labor",
      },
      {
        id: "job-additional-cost-demo-cost-2",
        label: "Cleaning solution",
        amount: 40,
        category: "parts",
      },
      {
        id: "job-additional-cost-demo-cost-3",
        label: "Vacuum equipment rental",
        amount: 60,
        category: "fees",
      },
    ],
    complianceChecklist: [
      {
        id: "job-additional-cost-demo-check-1",
        label: "Power isolation verified",
        completed: true,
        completedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        completedBy: "sp-emp-1",
      },
      {
        id: "job-additional-cost-demo-check-2",
        label: "Drain cleared",
        completed: false,
      },
    ],
    assignmentHistory: [
      {
        id: "job-additional-cost-demo-assign-1",
        targetType: "service_provider",
        serviceProviderId: "4",
        serviceProviderName: "Mike Johnson",
        assignedBy: "3",
        assignedByName: "Admin User",
        assignedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        scheduledDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        status: "accepted",
      },
    ],
    assignmentQueue: [],
    completionPhotos: [],
    additionalCosts: [],
    tenantName: "Ahmed Al-Rashid",
    tenantPhone: "+971 50 123 4567",
    estimate: {
      id: "job-additional-cost-demo-estimate",
      jobId: "job-additional-cost-demo",
      createdBy: "sp-emp-1",
      createdByName: "Ahmed Al-Mansoori",
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      status: "sp_approved",
      items: [
        {
          id: "job-additional-cost-demo-estimate-item-1",
          label: "Insulation wrap",
          amount: 85,
          category: "materials",
          description: "Foam insulation wrap for 2m drain line",
        },
        {
          id: "job-additional-cost-demo-estimate-item-2",
          label: "Additional labor",
          amount: 95,
          category: "labor",
          description: "One hour to install insulation and reseal access panel",
        },
      ],
      subtotal: 180,
      notes: "Prevents future condensation leaks; recommended before restarting unit.",
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      spApprovedBy: "4",
      spApprovedByName: "Mike Johnson",
      spDecisionAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    startedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    startedBy: "sp-emp-1",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Analytics data
export const DEFAULT_ANALYTICS: Analytics = {
  openJobsCount: 3,
  tenantsCount: 430,
  bookingsToday: 8,
  completedJobsThisMonth: 45,
  completionRate: 78.5,
  averageCompletionTime: 24, // hours
  averageRating: 4.5,
  totalRevenue: 125000,
  revenueThisMonth: 28500,
  pendingRequestsCount: 5,
  activeMaintenanceNotices: 2,
  buildingsCount: 4,
  occupancyRate: 92.3,
  topServiceProviders: [
    {
      id: "4",
      name: "Mike Johnson",
      jobsCompleted: 28,
      completedJobs: 28,
      averageRating: 4.7,
    },
    {
      id: "5",
      name: "Alex Wilson",
      jobsCompleted: 17,
      completedJobs: 17,
      averageRating: 4.3,
    },
  ],
  recentActivity: [
    {
      id: "act-1",
      type: "job",
      description: "AC Repair job assigned to Mike Johnson",
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-2",
      type: "request",
      description: "New plumbing request from Unit 1205",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-3",
      type: "booking",
      description: "Pool booking confirmed for tomorrow",
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-4",
      type: "notice",
      description: "Water maintenance notice published",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "act-5",
      type: "job",
      description: "Elevator maintenance completed",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// Permissions data
const PERMISSIONS: Permission[] = [
  // User permissions
  { id: "perm-1", resource: "users", action: "create", description: "Create new users" },
  { id: "perm-2", resource: "users", action: "read", description: "View user details" },
  { id: "perm-3", resource: "users", action: "update", description: "Update user information" },
  { id: "perm-4", resource: "users", action: "delete", description: "Delete users" },
  { id: "perm-5", resource: "users", action: "manage", description: "Full user management" },

  // Building permissions
  { id: "perm-6", resource: "buildings", action: "create", description: "Create new buildings" },
  { id: "perm-7", resource: "buildings", action: "read", description: "View building details" },
  { id: "perm-8", resource: "buildings", action: "update", description: "Update building information" },
  { id: "perm-9", resource: "buildings", action: "delete", description: "Delete buildings" },
  { id: "perm-10", resource: "buildings", action: "manage", description: "Full building management" },

  // Job permissions
  { id: "perm-11", resource: "jobs", action: "create", description: "Create new jobs" },
  { id: "perm-12", resource: "jobs", action: "read", description: "View job details" },
  { id: "perm-13", resource: "jobs", action: "update", description: "Update job information" },
  { id: "perm-14", resource: "jobs", action: "delete", description: "Delete jobs" },
  { id: "perm-15", resource: "jobs", action: "manage", description: "Full job management" },

  // Request permissions
  { id: "perm-16", resource: "requests", action: "create", description: "Create new requests" },
  { id: "perm-17", resource: "requests", action: "read", description: "View request details" },
  { id: "perm-18", resource: "requests", action: "update", description: "Update request status" },
  { id: "perm-19", resource: "requests", action: "delete", description: "Delete requests" },
  { id: "perm-20", resource: "requests", action: "manage", description: "Full request management" },

  // Unit & inventory permissions
  { id: "perm-21", resource: "units", action: "read", description: "View unit inventory" },
  { id: "perm-22", resource: "units", action: "update", description: "Update unit details" },
  { id: "perm-23", resource: "units", action: "manage", description: "Full unit management" },
  { id: "perm-24", resource: "unit_types", action: "manage", description: "Manage unit type templates" },

  // Workforce permissions
  { id: "perm-25", resource: "employees", action: "manage", description: "Manage building employees" },
  { id: "perm-26", resource: "service_providers", action: "manage", description: "Manage service providers" },

  // Visitor & delivery management
  { id: "perm-27", resource: "visitors", action: "read", description: "View visitor and delivery logs" },
  { id: "perm-28", resource: "visitors", action: "manage", description: "Manage visitor and delivery access" },

  // Ratings insights
  { id: "perm-29", resource: "ratings", action: "read", description: "View ratings and reviews" },

  // Analytics permissions
  { id: "perm-30", resource: "analytics", action: "read", description: "View analytics dashboard" },
  { id: "perm-31", resource: "analytics", action: "manage", description: "Full analytics access" },

  // Permissions management
  { id: "perm-32", resource: "permissions", action: "read", description: "View permissions" },
  { id: "perm-33", resource: "permissions", action: "manage", description: "Manage role permissions" },
];

export const DEFAULT_ROLE_PERMISSIONS: RolePermissions[] = [
  {
    role: "super_admin",
    permissions: PERMISSIONS,
  },
  {
    role: "admin",
    permissions: PERMISSIONS, // Admin has all permissions
  },
  {
    role: "management",
    permissions: PERMISSIONS.filter(p =>
      [
        "users",
        "buildings",
        "jobs",
        "requests",
        "analytics",
        "units",
        "unit_types",
        "employees",
        "service_providers",
        "visitors",
        "ratings",
      ].includes(p.resource) &&
      ["read", "update", "manage"].includes(p.action)
    ),
  },
  {
    role: "service_provider",
    permissions: PERMISSIONS.filter(p =>
      ["jobs", "requests"].includes(p.resource) &&
      ["read", "update"].includes(p.action)
    ),
  },
  {
    role: "tenant",
    permissions: PERMISSIONS.filter(p =>
      ["requests"].includes(p.resource) &&
      ["create", "read"].includes(p.action)
    ),
  },
  {
    role: "employee",
    permissions: PERMISSIONS.filter(p =>
      ["requests", "jobs"].includes(p.resource) &&
      ["read"].includes(p.action)
    ),
  },
];
