import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  contentWrapper: {
    flex: 1,
  },
  createButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7034FF",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  tableContainer: {
    flex: 1,
  },
  cellText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  cellTextSmall: {
    fontSize: 13,
    color: "#6B7280",
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#111827",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    width: "100%",
    maxWidth: 500,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
  },
  modalSubtitle: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 4,
  },
  closeButton: {
    padding: 4,
  },
  modalScrollContent: {
    paddingBottom: 20,
    gap: 20,
  },
  buildingNameText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#7034FF",
    marginBottom: 16,
  },
  managerRow: {
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 16,
    gap: 6,
  },
  assignButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: "#7034FF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  assignButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  formGroup: {
    marginBottom: 16,
  },
  formRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  formGroupHalf: {
    flex: 1,
    marginBottom: 0,
  },
  sectionDivider: {
    marginTop: 8,
    marginBottom: 20,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: "#E5E7EB",
  },
  breakdownToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  breakdownToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  breakdownToggleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7034FF",
  },
  breakdownToggleHint: {
    fontSize: 12,
    color: "#9CA3AF",
  },
  breakdownContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  summaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  summaryCard: {
    flexBasis: "48%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  summaryMeta: {
    fontSize: 11,
    color: "#9CA3AF",
    marginTop: 2,
    fontWeight: "600",
  },
  capacitySection: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    marginBottom: 16,
  },
  capacityHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  capacityText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  progressBar: {
    height: 8,
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  capacitySubtext: {
    fontSize: 12,
    color: "#6B7280",
  },
  detailSection: {
    gap: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
  },
  detailCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  detailCardRowLeft: {
    flex: 1,
    paddingRight: 12,
  },
  detailCardRowRight: {
    alignItems: "flex-end",
    gap: 4,
  },
  detailCardTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#111827",
  },
  detailCardSubtitle: {
    fontSize: 13,
    color: "#6B7280",
  },
  detailMeta: {
    fontSize: 12,
    color: "#6B7280",
  },
  emptyDetailText: {
    fontSize: 13,
    color: "#9CA3AF",
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 8,
  },
  labelOptional: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 8,
  },
  hint: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 8,
    fontStyle: "italic",
  },
  input: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1F2937",
  },
  pickerContainer: {
    maxHeight: 200,
  },
  pickerOption: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginRight: 8,
    marginBottom: 8,
  },
  pickerOptionActive: {
    backgroundColor: "#7034FF",
    borderColor: "#7034FF",
  },
  pickerOptionText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
  },
  pickerOptionTextActive: {
    color: "#FFFFFF",
  },
  pickerOptionSubtext: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  statusButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  statusButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  statusButtonActive: {
    backgroundColor: "#7034FF",
    borderColor: "#7034FF",
  },
  statusButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
  },
  statusButtonTextActive: {
    color: "#FFFFFF",
  },
  amenitiesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  amenityChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
  },
  amenityChipActive: {
    backgroundColor: "#F3E8FF",
    borderColor: "#7034FF",
  },
  amenityChipText: {
    fontSize: 13,
    color: "#374151",
    fontWeight: "600",
  },
  amenityChipTextActive: {
    color: "#4C1D95",
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7034FF",
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
    gap: 8,
  },
  submitButtonDisabled: {
    backgroundColor: "#9CA3AF",
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  // Enhanced Details Modal Styles
  detailsModalFullScreen: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  detailsModalContainer: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  detailsModalHeader: {
    backgroundColor: "#7034FF",
    paddingTop: 20,
    paddingBottom: 24,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: "#7034FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  detailsHeaderTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  detailsCloseButton: {
    padding: 4,
  },
  detailsStatusBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
  },
  detailsStatusText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  detailsHeaderContent: {
    alignItems: "center",
  },
  buildingIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  detailsBuildingName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  detailsLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  detailsLocation: {
    fontSize: 14,
    color: "#E9D5FF",
  },
  detailsModalScrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  detailsManagerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  detailsManagerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  detailsManagerIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F3E8FF",
    alignItems: "center",
    justifyContent: "center",
  },
  detailsManagerInfo: {
    flex: 1,
  },
  detailsManagerLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 2,
  },
  detailsManagerName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
  },
  detailsAssignButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F3E8FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E9D5FF",
  },
  detailsAssignButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7034FF",
  },
  detailsCapacityCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  detailsCapacityHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  detailsCapacityIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3E8FF",
    alignItems: "center",
    justifyContent: "center",
  },
  detailsCapacityInfo: {
    flex: 1,
  },
  detailsCapacityLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 2,
  },
  detailsCapacityValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
  },
  detailsProgressBar: {
    height: 8,
    backgroundColor: "#F3F4F6",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 8,
  },
  detailsProgressFill: {
    height: "100%",
    borderRadius: 999,
  },
  detailsCapacitySubtext: {
    fontSize: 12,
    color: "#6B7280",
  },
  detailsStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
  },
  detailsStatCard: {
    flexBasis: "48%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  detailsStatCardSuccess: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  detailsStatCardInfo: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
  },
  detailsStatCardWarning: {
    backgroundColor: "#FEF3C7",
    borderColor: "#FDE68A",
  },
  detailsStatIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  detailsStatValue: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  detailsStatLabel: {
    fontSize: 13,
    color: "#6B7280",
    marginBottom: 4,
  },
  detailsStatMeta: {
    fontSize: 11,
    color: "#9CA3AF",
    fontWeight: "600",
  },
  detailsOccupancyBar: {
    height: 6,
    backgroundColor: "#E5E7EB",
    borderRadius: 3,
    marginTop: 8,
    overflow: "hidden",
  },
  detailsOccupancyFill: {
    height: "100%",
    backgroundColor: "#10B981",
    borderRadius: 3,
  },
  detailsOccupancyText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#059669",
    marginTop: 4,
  },
  detailsSection: {
    marginBottom: 24,
  },
  detailsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  detailsSectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
    flex: 1,
  },
  detailsCountBadge: {
    backgroundColor: "#7034FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  detailsCountBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  detailsSectionContent: {
    gap: 10,
  },
  detailsEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  detailsEmptyText: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 8,
  },
  detailsShowMoreText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7034FF",
    textAlign: "center",
    paddingVertical: 12,
    backgroundColor: "#F3E8FF",
    borderRadius: 8,
    marginTop: 4,
  },
  // Breakdown Display Styles
  breakdownDisplayContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    gap: 16,
  },
  breakdownItem: {
    gap: 8,
  },
  breakdownItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  breakdownItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  breakdownItemRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  breakdownDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  breakdownLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
  },
  breakdownCount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1F2937",
  },
  breakdownCountOverflow: {
    color: "#EF4444",
  },
  breakdownCountSeparator: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  breakdownCountPlanned: {
    fontSize: 14,
    color: "#6B7280",
  },
  breakdownProgress: {
    fontSize: 12,
    fontWeight: "600",
    color: "#9CA3AF",
    marginLeft: 4,
  },
  breakdownProgressComplete: {
    color: "#10B981",
  },
  breakdownBar: {
    height: 8,
    backgroundColor: "#F3F4F6",
    borderRadius: 4,
    overflow: "hidden",
  },
  breakdownBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  breakdownTotal: {
    borderTopWidth: 2,
    borderTopColor: "#E5E7EB",
    paddingTop: 16,
    gap: 8,
  },
  breakdownTotalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  breakdownTotalLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  breakdownTotalCount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7034FF",
  },
  breakdownTotalBar: {
    height: 12,
    backgroundColor: "#F3F4F6",
    borderRadius: 6,
    overflow: "hidden",
  },
  breakdownTotalBarFill: {
    height: "100%",
    backgroundColor: "#7034FF",
    borderRadius: 6,
  },
  breakdownTotalProgress: {
    fontSize: 13,
    fontWeight: "600",
    color: "#7034FF",
    textAlign: "center",
  },
});

export { styles };
